version: '3.8'

services:
  db:
    image: postgis/postgis:13-3.1
    restart: always
    env_file: 
      - credentials.env
    ports:
      - "4501:5432"
    volumes:
      - ./database/tables:/docker-entrypoint-initdb.d

  fastapi_api_offerus:
    build:
      context: ./app/.
      dockerfile: Dockerfile
    volumes:
      - ./app:/code
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: 
      - credentials.env
    command: >
      uvicorn api.main:app --host 0.0.0.0 --port 443
      --ssl-keyfile /etc/letsencrypt/live/offerus.ddns.net/privkey.pem
      --ssl-certfile /etc/letsencrypt/live/offerus.ddns.net/fullchain.pem
